"""
app/crud/wallet_crud.py

FIXES vs previous version:
  1.  [FINANCIAL INTEGRITY §5.6] idempotency_key UNIQUE NOT NULL added to
      every WalletTransaction creation. Generated by the caller (service layer)
      using uuid4. The CRUD receives it and stores it — it is NEVER auto-generated
      here so the caller always has a reference to the key before the DB write.

  2.  Wallet.user_id → Wallet.owner_id throughout. Blueprint §14.
      Wallet.is_active → Wallet.is_suspended. Blueprint §14.
      owner_type='customer'|'business'|'rider' added on creation.

  3.  WalletTransaction.reference_id → WalletTransaction.external_reference.
      Blueprint §14. The `external_reference` stores Monnify/Paystack reference.
      The `idempotency_key` is the internal unique key per operation.
      get_by_reference() queries external_reference AND idempotency_key.

  4.  CRUDCryptoTopUp class DELETED. Blueprint §5: Monnify + Paystack only.
      No crypto funding channel.

  5.  [HARD RULE §16.4] All datetime.utcnow() replaced with
      datetime.now(timezone.utc). This produces timezone-aware datetimes
      compatible with PostgreSQL TIMESTAMPTZ columns.

  6.  create_wallet_sync() kept for Blueprint §16.7:
      "Use create_wallet_sync() with a sync Session for wallet creation
      if called from a synchronous FastAPI handler."
      All Celery tasks use this because Celery workers are sync by default.
"""
import secrets
import uuid as _uuid
from datetime import datetime, date, timezone, timedelta
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID

from sqlalchemy import and_, func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Session

from app.crud.base_crud import AsyncCRUDBase as CRUDBase
from app.models.wallet_model import (
    PlatformRevenue,
    TransactionStatus,
    TransactionType,
    Wallet,
    WalletTransaction,
    generate_wallet_number,
)
from app.core.exceptions import (
    InsufficientBalanceException,
    NotFoundException,
    ValidationException,
)
from app.config import settings


# ─── JSON sanitiser (keeps asyncpg happy with JSONB columns) ─────────────────

def _sanitize_for_jsonb(obj):
    """Recursively convert non-JSON-serializable types (Decimal, UUID) to primitives."""
    if isinstance(obj, Decimal):
        return float(obj)
    if isinstance(obj, UUID):
        return str(obj)
    if isinstance(obj, dict):
        return {k: _sanitize_for_jsonb(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_sanitize_for_jsonb(v) for v in obj]
    return obj


# ─── Idempotency key generator ────────────────────────────────────────────────

def generate_idempotency_key() -> str:
    """
    Generate a unique idempotency key for a wallet transaction.
    Blueprint §5.6 HARD RULE: every financial operation uses an idempotency key.
    Callers (service layer) should generate this before any DB write so they
    can include it in external payment requests for correlation.
    """
    return f"TXN_{_uuid.uuid4().hex.upper()}"


# ─── Wallet CRUD ──────────────────────────────────────────────────────────────

class CRUDWallet(CRUDBase[Wallet, dict, dict]):
    """
    Wallet data access.

    Blueprint §14 schema:
      owner_id   UUID NOT NULL REFERENCES users(id)
      owner_type VARCHAR(20) CHECK IN ('customer','business','rider')
      is_suspended BOOLEAN NOT NULL DEFAULT FALSE
      virtual_acct_* Monnify account fields (nullable until provisioned)
      monnify_acct_ref VARCHAR(100) UNIQUE
    """

    # ── Lookups ───────────────────────────────────────────────────────────────

    async def get_by_owner(
        self, db: AsyncSession, *, owner_id: UUID
    ) -> Optional[Wallet]:
        """Get wallet by owner_id (Blueprint §14 field name)."""
        result = await db.execute(
            select(Wallet).where(Wallet.owner_id == owner_id)
        )
        return result.scalars().first()

    # Aliases for backward compat with service layer call sites
    async def get_by_user(
        self, db: AsyncSession, *, user_id: UUID
    ) -> Optional[Wallet]:
        return await self.get_by_owner(db, owner_id=user_id)

    async def get_by_user_id(
        self, db: AsyncSession, *, user_id: UUID
    ) -> Optional[Wallet]:
        return await self.get_by_owner(db, owner_id=user_id)

    async def get_by_id(
        self, db: AsyncSession, *, wallet_id: UUID
    ) -> Optional[Wallet]:
        result = await db.execute(
            select(Wallet).where(Wallet.id == wallet_id)
        )
        return result.scalars().first()

    async def get_by_wallet_number(
        self, db: AsyncSession, *, wallet_number: str
    ) -> Optional[Wallet]:
        result = await db.execute(
            select(Wallet).where(Wallet.wallet_number == wallet_number)
        )
        return result.scalars().first()

    # ── Create (async — for wallet service layer) ──────────────────────────────

    async def create_wallet(
        self,
        db: AsyncSession,
        *,
        owner_id: UUID,
        owner_type: str = "customer",
    ) -> Wallet:
        """
        Create a wallet.
        Blueprint §14: owner_id + owner_type (not user_id).
        Blueprint §16.7: use create_wallet_sync() from sync Celery tasks.
        """
        wallet_number = await self._unique_wallet_number_async(db)
        wallet = Wallet(
            owner_id=owner_id,
            owner_type=owner_type,
            wallet_number=wallet_number,
            balance=Decimal("0.00"),
            currency="NGN",
            is_suspended=False,     # Blueprint §14: is_suspended not is_active
        )
        db.add(wallet)
        await db.flush()
        return wallet

    # ── Create (sync — for Celery tasks and sync handlers) ────────────────────

    def create_wallet_sync(
        self,
        db: Session,
        *,
        owner_id: UUID,
        owner_type: str = "customer",
    ) -> Wallet:
        """
        Sync wallet creation.
        Blueprint §16.7: "Use create_wallet_sync() with a sync Session for
        wallet creation if called from a synchronous FastAPI handler.
        Async methods cannot be called from sync handlers."

        Called by:
          - Celery task create_wallet (sync worker environment)
          - sync registration handler (if wallet is created synchronously)
        """
        wallet_number = self._unique_wallet_number_sync(db)
        wallet = Wallet(
            owner_id=owner_id,
            owner_type=owner_type,
            wallet_number=wallet_number,
            balance=Decimal("0.00"),
            currency="NGN",
            is_suspended=False,
        )
        db.add(wallet)
        db.commit()
        db.refresh(wallet)
        return wallet

    # ── Credit ────────────────────────────────────────────────────────────────

    async def credit_wallet(
        self,
        db: AsyncSession,
        *,
        wallet_id: UUID,
        amount: Decimal,
        transaction_type: TransactionType,
        description: str,
        idempotency_key: str,                   # Blueprint §5.6 HARD RULE: REQUIRED
        external_reference: Optional[str] = None,  # Monnify/Paystack reference
        related_order_id: Optional[UUID] = None,
        related_booking_id: Optional[UUID] = None,
        metadata: Optional[dict] = None,
    ) -> WalletTransaction:
        """
        Credit a wallet atomically.
        Blueprint §5.6 HARD RULE: idempotency_key UNIQUE NOT NULL.
        Caller must generate idempotency_key before calling this.
        Do NOT commit inside — caller commits for full atomicity.
        """
        result = await db.execute(select(Wallet).where(Wallet.id == wallet_id))
        wallet = result.scalars().first()
        if not wallet:
            raise NotFoundException("Wallet")
        if amount <= 0:
            raise ValidationException("Amount must be positive")
        if wallet.is_suspended:
            raise ValidationException("Wallet is suspended. Contact support.")

        max_bal = Decimal(str(getattr(settings, "WALLET_MAX_BALANCE", 10_000_000)))
        if wallet.balance + amount > max_bal:
            raise ValidationException("Maximum wallet balance exceeded")

        balance_before = wallet.balance
        wallet.balance += amount

        txn = WalletTransaction(
            wallet_id=wallet_id,
            transaction_type=transaction_type,
            amount=amount,
            balance_before=balance_before,
            balance_after=wallet.balance,
            status=TransactionStatus.COMPLETED,
            description=description,
            # Blueprint §5.6 HARD RULE: idempotency_key UNIQUE NOT NULL
            idempotency_key=idempotency_key,
            # Blueprint §14: external_reference = Monnify/Paystack reference
            external_reference=external_reference,
            related_order_id=related_order_id,
            related_booking_id=related_booking_id,
            meta_data=_sanitize_for_jsonb(metadata) if metadata else None,
            # Blueprint §16.4 HARD RULE: timezone-aware UTC timestamp
            completed_at=datetime.now(timezone.utc),
        )
        db.add(txn)
        return txn  # caller commits

    # ── Debit ─────────────────────────────────────────────────────────────────

    async def debit_wallet(
        self,
        db: AsyncSession,
        *,
        wallet_id: UUID,
        amount: Decimal,
        transaction_type: TransactionType,
        description: str,
        idempotency_key: str,                   # Blueprint §5.6 HARD RULE: REQUIRED
        external_reference: Optional[str] = None,
        related_order_id: Optional[UUID] = None,
        related_booking_id: Optional[UUID] = None,
        metadata: Optional[dict] = None,
    ) -> WalletTransaction:
        """
        Debit a wallet atomically.
        Blueprint §5.6 HARD RULE: idempotency_key UNIQUE NOT NULL.
        Do NOT commit inside — caller commits for full atomicity.
        """
        result = await db.execute(select(Wallet).where(Wallet.id == wallet_id))
        wallet = result.scalars().first()
        if not wallet:
            raise NotFoundException("Wallet")
        if amount <= 0:
            raise ValidationException("Amount must be positive")
        if wallet.is_suspended:
            raise ValidationException("Wallet is suspended. Contact support.")
        if wallet.balance < amount:
            raise InsufficientBalanceException()

        balance_before = wallet.balance
        wallet.balance -= amount

        txn = WalletTransaction(
            wallet_id=wallet_id,
            transaction_type=transaction_type,
            amount=amount,
            balance_before=balance_before,
            balance_after=wallet.balance,
            status=TransactionStatus.COMPLETED,
            description=description,
            idempotency_key=idempotency_key,
            external_reference=external_reference,
            related_order_id=related_order_id,
            related_booking_id=related_booking_id,
            meta_data=_sanitize_for_jsonb(metadata) if metadata else None,
            completed_at=datetime.now(timezone.utc),
        )
        db.add(txn)
        return txn  # caller commits

    # ── Wallet number uniqueness helpers ──────────────────────────────────────

    async def _unique_wallet_number_async(
        self, db: AsyncSession, max_tries: int = 10
    ) -> str:
        for _ in range(max_tries):
            number = generate_wallet_number()
            result = await db.execute(
                select(Wallet).where(Wallet.wallet_number == number)
            )
            if result.scalars().first() is None:
                return number
        raise RuntimeError("Could not generate unique wallet number after retries")

    def _unique_wallet_number_sync(
        self, db: Session, max_tries: int = 10
    ) -> str:
        for _ in range(max_tries):
            number = generate_wallet_number()
            if not db.query(Wallet).filter(Wallet.wallet_number == number).first():
                return number
        raise RuntimeError("Could not generate unique wallet number after retries")


# ─── Wallet Transaction CRUD ──────────────────────────────────────────────────

class CRUDWalletTransaction(CRUDBase[WalletTransaction, dict, dict]):

    async def get_by_idempotency_key(
        self, db: AsyncSession, *, idempotency_key: str
    ) -> Optional[WalletTransaction]:
        """
        Primary idempotency check.
        Blueprint §5.6: idempotency_key UNIQUE NOT NULL.
        """
        result = await db.execute(
            select(WalletTransaction).where(
                WalletTransaction.idempotency_key == idempotency_key
            )
        )
        return result.scalars().first()

    async def get_by_external_reference(
        self, db: AsyncSession, *, external_reference: str
    ) -> Optional[WalletTransaction]:
        """
        Secondary idempotency check.
        Blueprint §14: external_reference = Monnify/Paystack reference (UNIQUE).
        Blueprint §5.5: "idempotency key = monnify_transaction_reference,
        stored in wallet_transactions.external_reference — UNIQUE constraint"
        """
        result = await db.execute(
            select(WalletTransaction).where(
                WalletTransaction.external_reference == external_reference
            )
        )
        return result.scalars().first()

    # Backward-compat alias used by wallet_service
    async def get_by_reference(
        self, db: AsyncSession, *, reference_id: str
    ) -> Optional[WalletTransaction]:
        """Try idempotency_key first, then external_reference."""
        txn = await self.get_by_idempotency_key(db, idempotency_key=reference_id)
        if txn:
            return txn
        return await self.get_by_external_reference(db, external_reference=reference_id)

    async def get_wallet_transactions(
        self,
        db: AsyncSession,
        *,
        wallet_id: UUID,
        transaction_type: Optional[TransactionType] = None,
        skip: int = 0,
        limit: int = 20,
    ) -> Tuple[List[WalletTransaction], int]:
        query = select(WalletTransaction).where(
            WalletTransaction.wallet_id == wallet_id
        )
        count_q = select(func.count()).select_from(WalletTransaction).where(
            WalletTransaction.wallet_id == wallet_id
        )
        if transaction_type:
            query   = query.where(WalletTransaction.transaction_type == transaction_type)
            count_q = count_q.where(WalletTransaction.transaction_type == transaction_type)

        query = (
            query
            .order_by(WalletTransaction.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        result       = await db.execute(query)
        count_result = await db.execute(count_q)
        return list(result.scalars().all()), count_result.scalar_one()


# ─── Platform Revenue CRUD ────────────────────────────────────────────────────

class CRUDPlatformRevenue(CRUDBase[PlatformRevenue, dict, dict]):
    """
    Blueprint §5.4 / §11.3: immutable audit trail of all platform fees.
    """

    async def create_revenue_record(
        self,
        db: AsyncSession,
        *,
        customer_transaction_id: UUID,
        business_transaction_id: UUID,
        customer_id: UUID,
        business_id: UUID,
        gross_amount: Decimal,      # product_price + customer_fee
        platform_fee: Decimal,      # customer_fee + business_fee (total platform take)
        net_amount: Decimal,        # product_price - business_fee
        transaction_type: str,
        transaction_reference: str,
        related_entity_id: Optional[UUID] = None,
        description: Optional[str] = None,
        metadata: Optional[dict] = None,
    ) -> PlatformRevenue:
        """
        Create a platform revenue record.
        Called INSIDE the same DB transaction as the wallet debits/credits.
        Caller must flush before calling (so transaction IDs are populated).
        Caller commits for full atomicity.
        """
        revenue = PlatformRevenue(
            customer_transaction_id=customer_transaction_id,
            business_transaction_id=business_transaction_id,
            customer_id=customer_id,
            business_id=business_id,
            gross_amount=gross_amount,
            platform_fee=platform_fee,
            net_amount=net_amount,
            transaction_type=transaction_type,
            transaction_reference=transaction_reference,
            related_entity_id=related_entity_id,
            description=description,
            meta_data=_sanitize_for_jsonb(metadata) if metadata else None,
        )
        db.add(revenue)
        return revenue  # caller commits

    async def get_by_reference(
        self, db: AsyncSession, *, reference: str
    ) -> Optional[PlatformRevenue]:
        result = await db.execute(
            select(PlatformRevenue).where(
                PlatformRevenue.transaction_reference == reference
            )
        )
        return result.scalars().first()

    async def get_by_entity(
        self, db: AsyncSession, *, entity_id: UUID
    ) -> Optional[PlatformRevenue]:
        result = await db.execute(
            select(PlatformRevenue).where(
                PlatformRevenue.related_entity_id == entity_id
            )
        )
        return result.scalars().first()

    async def get_revenue_list(
        self,
        db: AsyncSession,
        *,
        transaction_type: Optional[str] = None,
        customer_id: Optional[UUID] = None,
        business_id: Optional[UUID] = None,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        skip: int = 0,
        limit: int = 20,
    ) -> Tuple[List[PlatformRevenue], int]:
        query   = select(PlatformRevenue)
        count_q = select(func.count()).select_from(PlatformRevenue)

        filters = []
        if transaction_type:
            filters.append(PlatformRevenue.transaction_type == transaction_type)
        if customer_id:
            filters.append(PlatformRevenue.customer_id == customer_id)
        if business_id:
            filters.append(PlatformRevenue.business_id == business_id)
        if start_date:
            # Blueprint §16.4 HARD RULE: timezone-aware datetime
            start_dt = datetime(
                start_date.year, start_date.month, start_date.day,
                tzinfo=timezone.utc,
            )
            filters.append(PlatformRevenue.created_at >= start_dt)
        if end_date:
            end_dt = datetime(
                end_date.year, end_date.month, end_date.day, 23, 59, 59,
                tzinfo=timezone.utc,
            )
            filters.append(PlatformRevenue.created_at <= end_dt)

        if filters:
            query   = query.where(and_(*filters))
            count_q = count_q.where(and_(*filters))

        query = (
            query
            .order_by(PlatformRevenue.created_at.desc())
            .offset(skip)
            .limit(limit)
        )

        result       = await db.execute(query)
        count_result = await db.execute(count_q)
        return list(result.scalars().all()), count_result.scalar_one()

    async def get_total_revenue(
        self,
        db: AsyncSession,
        *,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> Decimal:
        query   = select(func.sum(PlatformRevenue.platform_fee))
        filters = []
        if start_date:
            filters.append(PlatformRevenue.created_at >= datetime(
                start_date.year, start_date.month, start_date.day, tzinfo=timezone.utc
            ))
        if end_date:
            filters.append(PlatformRevenue.created_at <= datetime(
                end_date.year, end_date.month, end_date.day, 23, 59, 59, tzinfo=timezone.utc
            ))
        if filters:
            query = query.where(and_(*filters))
        result = await db.execute(query)
        return result.scalar_one_or_none() or Decimal("0")


# ─── Singletons ───────────────────────────────────────────────────────────────

wallet_crud             = CRUDWallet(Wallet)
wallet_transaction_crud = CRUDWalletTransaction(WalletTransaction)
transaction_crud        = wallet_transaction_crud      # alias
platform_revenue_crud   = CRUDPlatformRevenue(PlatformRevenue)